### ISSUE TITLE
Adding the Hebrew language

### ISSUE THREAD

**Issue by YOSI-COHEN** [basharast/wut#1]
Hello and thanks for the software
Is it possible to add a Hebrew language, as well as a download from Google Drive?
Thanks

**Comment by YOSI-COHEN** [comment]
And if it is possible to add the telegram
Thanks

**Comment by basharast** [comment]
## Translation

I prepared the translation file, the translation generated using Google
Need correction and improvements. 
if will be able to verify the translations and correct the wrong sentence it will be great.

- Download it from Here [Resources.zip](https://github.com/basharast/wut/files/7898149/Resources.zip)
- Open it using any text editor (After extract)
- Try to be aware for the file structure (don't worry I can fix it if any thing went wrong)

## Google Drive

I will try to find some solutions for that

## Telegram

Sorry I didn't understand the telegram part (what telegram need to be added)?

Thanks.

**Comment by YOSI-COHEN** [comment]
Thank you very much.
But you did not translate into Hebrew You translated into another language it is Hebrew
It's Hebrew
(אבגדהוזחטיכלמנסעפצקרשת)
Thanks so much for adding Google Drive

It's a telegram
https://web.telegram.org/

**Comment by basharast** [comment]
> Thank you very much. But you did not translate into Hebrew You translated into another language it is Hebrew It's Hebrew (אבגדהוזחטיכלמנסעפצקרשת) Thanks so much for adding Google Drive
> 
> It's a telegram https://web.telegram.org/

Oh sorry, my mistake.. I updated the attachment
Please re-download it again [Resources.zip](https://github.com/basharast/wut/files/7898388/Resources.zip)

**Comment by YOSI-COHEN** [comment]
Yes thank you it is hebrew
How to add it to software

**Comment by basharast** [comment]
> 

Once you fixed the translations, send it back (attached) here as ".zip" file
I will added it along with the next update.

**Comment by YOSI-COHEN** [comment]
On the face of it the translation seems very good, I will update you on mistakes

**Comment by YOSI-COHEN** [comment]
Greetings
I have a few more additions that I would be happy if you add
A. Download video from reddit
B. Download video from various sites
third. Download apps from Google Wonders
D. Can you upload the Hebrew version (at least to me)

Thank you so much for all the additions and I'm sorry if I bother you

**Comment by basharast** [comment]
It's OK, I will be happy to help,
I will add the first 2 points to 'TO-DO' list, 
You can download the Hebrew release from the link below:
[https://mega.nz/file/fhpiHCjY#Nx74xb1BNoHiQkBEMtOs0Y4Mph0oH64tWb7B8Upoq6E](url)
