### ISSUE TITLE
Strange notice and cannot download files

### ISSUE THREAD

**Issue by Stragytek** [basharast/wut#18]
![IMG_20240112_235704](https://github.com/basharast/wut/assets/104332460/efa968c6-987e-4f84-91a7-8fef745afc32)
![IMG_20240112_235744](https://github.com/basharast/wut/assets/104332460/ae7bbf6c-922e-4748-92eb-17d7346012dc)
I do all the same thing like u guys on Youtube, but when I click on Repositories, while loading, this strange notice appeared "File changed or deleted.." but it still loading successful like the image, and when I shut that notice to try to download some game or app, I can't because of the second notice "One or more errors occurred....", can u help me with this ? Thanks, and sr if my EN not very well.

**Comment by basharast** [comment]
Hi, 
## First error
the first issue I think related to the XBL games repo, it seems not accessible for now for some reason
I don't maintain those repos so I have no idea why it's not working.

## Second error
Files are hosted in MEGA.io, there is limited bandwidth per user for downloads each day
you need to wait few hours then try again.
I think the limit is ~5GB daily (from MEGA.io side not ours).

**Comment by Stragytek** [comment]
Thank u
