### ISSUE TITLE
Games do not work after downloading from the store

### ISSUE THREAD

**Issue by YOSI-COHEN** [basharast/wut#4]
When I download from Microsoft Store and install, it shows me an error.
He never played the game for me
This is the error:
![image](https://user-images.githubusercontent.com/82176699/174303834-fc2f1135-1a98-49b4-851f-5f7eb14683f8.png)

**Comment by YOSI-COHEN** [comment]
By the way, I translated the help into Hebrew.
In the next version you will upload it:
[WUT Commander.docx](https://github.com/basharast/wut/files/8927754/WUT.Commander.docx)

**Comment by basharast** [comment]
> 

Many thanks I uploaded the file to WUT Home.

**Comment by basharast** [comment]
> When I download from Microsoft Store and install, it shows me an error. He never played the game for me This is the error: ![image](https://user-images.githubusercontent.com/82176699/174303834-fc2f1135-1a98-49b4-851f-5f7eb14683f8.png)

You cannot use any app in the store, some apps/games required license to work (specifically the paid apps/games)
even if it installed successfully it will not start.

**Comment by YOSI-COHEN** [comment]
These are regular games, which I download through the software.

**Comment by YOSI-COHEN** [comment]
Well, I'll just remind you when you become available, add an option to download through another server, and add a download option from Google Wonders.

Thank you very much!!!

By the way, you can link to this topic:
"Microsoft Store Search (Originally by StoreDev & Media Explorer)"
Thanks.

**Comment by basharast** [comment]
- Issue added to TO-DO list at WUT private repository, it will be considered to be solved next update.
- Google drive already added to features list.

WUT store feature taken and powered by [StoreLib](https://github.com/StoreDev/StoreLib) by [StoreDev](https://github.com/StoreDev) only, Media Explorer already mentioned in About page as he helped to bring this good idea so I'm not sure if he was involved in StoreLib development.

I will close this for now as it's already moved to the list, I can track it from there
I will inform you once the update ready.

Thanks.

**Comment by YOSI-COHEN** [comment]
What a good person you are!
![gettyimages-458686694-612x612](https://user-images.githubusercontent.com/82176699/174598023-8fdd4281-dcb2-42ba-84f8-d490bab75390.jpg)
