### ISSUE TITLE
 A Prerequisite for an install could not be satisfied. (0x80073cfd) 

### ISSUE THREAD

**Issue by Christopherart** [basharast/wut#6]
when i try to install i get this error

**Comment by basharast** [comment]
It depends on which device are you trying to install.
mostly you will see this message with Windows Phone
if this is the case:

- be sure to download and install the **ARM32** version NOT **ARM64**
- you must have your system updated to 15063 other wise get the 14393 version.

## WUT ARM32 download link
https://github.com/basharast/wut/releases/download/1.4.11/WUT.1.4.11_ARM.7z

## WUT ARM32 (14393) download link
https://github.com/basharast/wut/releases/download/1.4.11/WUT.1.4.11_ARM.14393.7z
